import Head from "next/head";
import React, { useState, useEffect } from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import dataEng from "../src/data/english.json";
import dataHindi from "../src/data/hindi.json";
import MainContent from "../components/MainContent";

export default function Home() {
  const [content, setContent] = useState(dataEng);
  useEffect(() => {
    console.log(content);
  }, [content]);
  const changeLang = () => {
    if (content === dataEng) {
      setContent(dataHindi);
    } else {
      setContent(dataEng);
    }
  };

  return (
    <div>
      <Head key="ss">
        <title key="jhgsgd">Create Next App</title>
        <meta
          key="jhsd"
          name="description"
          content="Generated by create next app"
        />
        <link key="{ff}" rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        dataHindi={dataHindi}
        dataEng={dataEng}
        lang={content}
        changeContent={changeLang}
      />
      <Hero data={content} />
      <MainContent data={content} />
      <Footer />
    </div>
  );
}
